#!/usr/bin/env python3
"""
MEMBRA L0 SDK Factory

Generates:
- TypeScript Solana/Anchor client adapter
- Python MEMBRA L0 client adapter
- README with generated routes

No API keys required.
Default network: Solana devnet.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict


def load_manifest(path: str) -> Dict[str, Any]:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.strip() + "\n", encoding="utf-8")


def ts_sdk(manifest: Dict[str, Any]) -> str:
    mir_program = manifest["solana"]["programs"]["membra_mir"]["program_id"]
    gateway_program = manifest["solana"]["programs"]["membra_gateway"]["program_id"]
    rpc = manifest["network"]["default_rpc"]

    return f"""
/**
 * GENERATED BY MEMBRA L0 SDK FACTORY
 *
 * Solana devnet adapter for MEMBRA MIR/M5/MCR primitives.
 *
 * This file intentionally stores no secrets.
 * Wallet signing must happen through a wallet adapter, local keypair,
 * or controlled devnet signer.
 */

import * as anchor from "@coral-xyz/anchor";
import {{
  Connection,
  PublicKey,
  Transaction,
  TransactionInstruction
}} from "@solana/web3.js";

export const MEMBRA_DEFAULT_RPC = "{rpc}";
export const MEMBRA_MIR_PROGRAM_ID = new PublicKey("{mir_program}");
export const MEMBRA_GATEWAY_PROGRAM_ID = new PublicKey("{gateway_program}");

export type PolicyTier = "Low" | "Medium" | "High" | "Critical";

export type CreateMirInput = {{
  agentIdHash: number[];
  jobIdHash: number[];
  inputHash: number[];
  contextHash: number[];
  modelIdHash: number[];
  policyTier: PolicyTier;
  selectedNodeCount: number;
  quorumRequired: number;
  rewardAmount: anchor.BN;
}};

export type AttestMirInput = {{
  receipt: PublicKey;
  node: PublicKey;
  attestationHash: number[];
  outputHash: number[];
  latencyMs: anchor.BN;
  tokenCount: anchor.BN;
  resourceScore: anchor.BN;
  approved: boolean;
}};

export class MembraSolanaClient {{
  connection: Connection;
  provider: anchor.AnchorProvider;
  mirProgram: anchor.Program;

  constructor(provider: anchor.AnchorProvider, mirIdl: anchor.Idl) {{
    this.provider = provider;
    this.connection = provider.connection;
    this.mirProgram = new anchor.Program(mirIdl, MEMBRA_MIR_PROGRAM_ID, provider);
  }}

  static devnetConnection(): Connection {{
    return new Connection(MEMBRA_DEFAULT_RPC, "confirmed");
  }}

  deriveMirPda(creator: PublicKey, jobIdHash: Uint8Array): [PublicKey, number] {{
    return PublicKey.findProgramAddressSync(
      [
        Buffer.from("mir"),
        creator.toBuffer(),
        Buffer.from(jobIdHash)
      ],
      MEMBRA_MIR_PROGRAM_ID
    );
  }}

  deriveM5NodePda(authority: PublicKey, nodeIdHash: Uint8Array): [PublicKey, number] {{
    return PublicKey.findProgramAddressSync(
      [
        Buffer.from("m5-node"),
        authority.toBuffer(),
        Buffer.from(nodeIdHash)
      ],
      MEMBRA_MIR_PROGRAM_ID
    );
  }}

  async createMirIx(input: CreateMirInput): Promise<TransactionInstruction> {{
    const creator = this.provider.wallet.publicKey;
    const [receipt] = this.deriveMirPda(creator, Uint8Array.from(input.jobIdHash));

    return await this.mirProgram.methods
      .createMir(
        input.agentIdHash,
        input.jobIdHash,
        input.inputHash,
        input.contextHash,
        input.modelIdHash,
        {{ [input.policyTier.toLowerCase()]: {{}} }},
        input.selectedNodeCount,
        input.quorumRequired,
        input.rewardAmount
      )
      .accounts({{
        receipt,
        creator,
        systemProgram: anchor.web3.SystemProgram.programId
      }})
      .instruction();
  }}

  async createMirTransaction(input: CreateMirInput): Promise<Transaction> {{
    const ix = await this.createMirIx(input);
    return new Transaction().add(ix);
  }}

  async sendPreparedTransaction(tx: Transaction): Promise<string> {{
    const signature = await this.provider.sendAndConfirm(tx, []);
    return signature;
  }}

  async createAndSendMir(input: CreateMirInput): Promise<string> {{
    const tx = await this.createMirTransaction(input);
    return await this.sendPreparedTransaction(tx);
  }}

  async fetchMir(receipt: PublicKey): Promise<any> {{
    return await this.mirProgram.account.mirReceipt.fetch(receipt);
  }}
}}
"""


def py_sdk(manifest: Dict[str, Any]) -> str:
    rpc = manifest["network"]["default_rpc"]
    network = manifest["network"]["name"]

    return f"""
\"\"\"
GENERATED BY MEMBRA L0 SDK FACTORY

Python MEMBRA L0 client adapter.

This client does not custody funds.
It builds local proof objects and prepares Solana-devnet-compatible payloads.
\"\"\"

from __future__ import annotations

import hashlib
import json
import time
import uuid
from dataclasses import dataclass, asdict, field
from typing import Any, Dict, List, Optional


MEMBRA_NETWORK = "{network}"
MEMBRA_DEFAULT_RPC = "{rpc}"


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8", errors="ignore")).hexdigest()


def sha256_json(value: Any) -> str:
    return hashlib.sha256(
        json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()


@dataclass
class MIR:
    mir_id: str = field(default_factory=lambda: "mir_" + uuid.uuid4().hex)
    job_id: str = field(default_factory=lambda: "job_" + uuid.uuid4().hex)
    agent_id: str = "agent_unknown"
    input_hash: str = ""
    context_hash: str = ""
    output_hash: str = ""
    model_id_hash: str = ""
    policy_tier: str = "Low"
    selected_m5_nodes: List[str] = field(default_factory=list)
    quorum_required: int = 1
    quorum_reached: bool = False
    created_at: int = field(default_factory=lambda: int(time.time()))
    devnet_tx: Optional[str] = None

    def root(self) -> str:
        return sha256_json(asdict(self))


@dataclass
class M5NodeClaim:
    node_id: str
    authority: str
    hardware_hash: str
    model_manifest_hash: str
    stake_score: int
    reputation_score: int = 100

    def root(self) -> str:
        return sha256_json(asdict(self))


@dataclass
class MCR:
    mcr_id: str = field(default_factory=lambda: "mcr_" + uuid.uuid4().hex)
    owner_wallet: str = "unknown"
    repo_merkle_root: str = ""
    memory_root: str = ""
    mir_roots: List[str] = field(default_factory=list)
    m5_attestation_root: str = ""
    collateral_score: int = 0
    appraisal_low_usd: int = 0
    appraisal_high_usd: int = 0
    created_at: int = field(default_factory=lambda: int(time.time()))
    devnet_tx: Optional[str] = None

    def root(self) -> str:
        return sha256_json(asdict(self))


class MembraL0Client:
    def __init__(self, rpc_url: str = MEMBRA_DEFAULT_RPC):
        self.rpc_url = rpc_url
        self.local_mirs: Dict[str, MIR] = {{}}
        self.local_mcrs: Dict[str, MCR] = {{}}

    def create_mir(
        self,
        agent_id: str,
        prompt_or_job_summary: str,
        context_summary: str,
        model_id: str,
        policy_tier: str = "Low",
        selected_m5_nodes: Optional[List[str]] = None,
        quorum_required: int = 1,
    ) -> MIR:
        mir = MIR(
            agent_id=agent_id,
            input_hash=sha256_text(prompt_or_job_summary),
            context_hash=sha256_text(context_summary),
            model_id_hash=sha256_text(model_id),
            policy_tier=policy_tier,
            selected_m5_nodes=selected_m5_nodes or [],
            quorum_required=quorum_required,
        )
        self.local_mirs[mir.mir_id] = mir
        return mir

    def complete_mir(self, mir_id: str, output_summary: str, quorum_reached: bool = True) -> MIR:
        mir = self.local_mirs[mir_id]
        mir.output_hash = sha256_text(output_summary)
        mir.quorum_reached = quorum_reached
        return mir

    def create_mcr(
        self,
        owner_wallet: str,
        repo_merkle_root: str,
        memory_root: str,
        mir_ids: List[str],
        m5_attestation_root: str,
        collateral_score: int,
        appraisal_low_usd: int,
        appraisal_high_usd: int,
    ) -> MCR:
        mir_roots = [self.local_mirs[mid].root() for mid in mir_ids]
        mcr = MCR(
            owner_wallet=owner_wallet,
            repo_merkle_root=repo_merkle_root,
            memory_root=memory_root,
            mir_roots=mir_roots,
            m5_attestation_root=m5_attestation_root,
            collateral_score=collateral_score,
            appraisal_low_usd=appraisal_low_usd,
            appraisal_high_usd=appraisal_high_usd,
        )
        self.local_mcrs[mcr.mcr_id] = mcr
        return mcr

    def prepare_solana_payload(self, obj: Any) -> Dict[str, Any]:
        \"\"\"
        Returns a Solana-devnet-ready payload.
        Actual signing/sending is handled by the TypeScript Anchor client
        or a local Solana signer.
        \"\"\"
        data = asdict(obj)
        return {{
            "network": MEMBRA_NETWORK,
            "cluster": "solana-devnet",
            "object_type": obj.__class__.__name__,
            "object_root": obj.root(),
            "payload": data,
            "raw_private_data_included": False,
        }}
"""


def readme(manifest: Dict[str, Any]) -> str:
    return f"""
# Generated MEMBRA L0 SDK

Generated from `membra.network.json`.

## Network

- Name: {manifest["network"]["name"]}
- Layer: {manifest["network"]["layer"]}
- Environment: {manifest["network"]["environment"]}
- Default RPC: {manifest["network"]["default_rpc"]}

## Generated clients

- `membra_solana_sdk.ts` 
- `membra_l0_sdk.py` 

## Primitive flow

1. Create MIR locally.
2. Register MIR on Solana devnet through Anchor.
3. M5 node attests inference or compute.
4. Quorum validates the receipt.
5. MCR binds repo proof, memory proof, MIR roots, and collateral score.
6. MEMBRA L0 uses this state for appraisal, rewards, routing, and transaction sponsorship.

## Privacy rule

No raw source code, private prompts, secrets, private keys, or chain-of-thought should be sent on-chain.
Only hashes, summaries, attestations, and settlement metadata are registered.
"""


def main() -> None:
    manifest = load_manifest("membra.network.json")
    out = Path("generated_sdk")

    write(out / "membra_solana_sdk.ts", ts_sdk(manifest))
    write(out / "membra_l0_sdk.py", py_sdk(manifest))
    write(out / "README.md", readme(manifest))

    print("Generated MEMBRA SDK files:")
    print(f"- {out / 'membra_solana_sdk.ts'}")
    print(f"- {out / 'membra_l0_sdk.py'}")
    print(f"- {out / 'README.md'}")


if __name__ == "__main__":
    main()
