/**
 * GENERATED BY MEMBRA L0 SDK FACTORY
 *
 * Solana devnet adapter for MEMBRA MIR/M5/MCR primitives.
 *
 * This file intentionally stores no secrets.
 * Wallet signing must happen through a wallet adapter, local keypair,
 * or controlled devnet signer.
 */

import * as anchor from "@coral-xyz/anchor";
import {
  Connection,
  PublicKey,
  Transaction,
  TransactionInstruction
} from "@solana/web3.js";

export const MEMBRA_DEFAULT_RPC = "https://api.devnet.solana.com";
export const MEMBRA_MIR_PROGRAM_ID = new PublicKey("REPLACE_WITH_MEMBRA_MIR_PROGRAM_ID");
export const MEMBRA_GATEWAY_PROGRAM_ID = new PublicKey("REPLACE_WITH_GATEWAY_PROGRAM_ID");

export type PolicyTier = "Low" | "Medium" | "High" | "Critical";

export type CreateMirInput = {
  agentIdHash: number[];
  jobIdHash: number[];
  inputHash: number[];
  contextHash: number[];
  modelIdHash: number[];
  policyTier: PolicyTier;
  selectedNodeCount: number;
  quorumRequired: number;
  rewardAmount: anchor.BN;
};

export type AttestMirInput = {
  receipt: PublicKey;
  node: PublicKey;
  attestationHash: number[];
  outputHash: number[];
  latencyMs: anchor.BN;
  tokenCount: anchor.BN;
  resourceScore: anchor.BN;
  approved: boolean;
};

export class MembraSolanaClient {
  connection: Connection;
  provider: anchor.AnchorProvider;
  mirProgram: anchor.Program;

  constructor(provider: anchor.AnchorProvider, mirIdl: anchor.Idl) {
    this.provider = provider;
    this.connection = provider.connection;
    this.mirProgram = new anchor.Program(mirIdl, MEMBRA_MIR_PROGRAM_ID, provider);
  }

  static devnetConnection(): Connection {
    return new Connection(MEMBRA_DEFAULT_RPC, "confirmed");
  }

  deriveMirPda(creator: PublicKey, jobIdHash: Uint8Array): [PublicKey, number] {
    return PublicKey.findProgramAddressSync(
      [
        Buffer.from("mir"),
        creator.toBuffer(),
        Buffer.from(jobIdHash)
      ],
      MEMBRA_MIR_PROGRAM_ID
    );
  }

  deriveM5NodePda(authority: PublicKey, nodeIdHash: Uint8Array): [PublicKey, number] {
    return PublicKey.findProgramAddressSync(
      [
        Buffer.from("m5-node"),
        authority.toBuffer(),
        Buffer.from(nodeIdHash)
      ],
      MEMBRA_MIR_PROGRAM_ID
    );
  }

  async createMirIx(input: CreateMirInput): Promise<TransactionInstruction> {
    const creator = this.provider.wallet.publicKey;
    const [receipt] = this.deriveMirPda(creator, Uint8Array.from(input.jobIdHash));

    return await this.mirProgram.methods
      .createMir(
        input.agentIdHash,
        input.jobIdHash,
        input.inputHash,
        input.contextHash,
        input.modelIdHash,
        { [input.policyTier.toLowerCase()]: {} },
        input.selectedNodeCount,
        input.quorumRequired,
        input.rewardAmount
      )
      .accounts({
        receipt,
        creator,
        systemProgram: anchor.web3.SystemProgram.programId
      })
      .instruction();
  }

  async createMirTransaction(input: CreateMirInput): Promise<Transaction> {
    const ix = await this.createMirIx(input);
    return new Transaction().add(ix);
  }

  async sendPreparedTransaction(tx: Transaction): Promise<string> {
    const signature = await this.provider.sendAndConfirm(tx, []);
    return signature;
  }

  async createAndSendMir(input: CreateMirInput): Promise<string> {
    const tx = await this.createMirTransaction(input);
    return await this.sendPreparedTransaction(tx);
  }

  async fetchMir(receipt: PublicKey): Promise<any> {
    return await this.mirProgram.account.mirReceipt.fetch(receipt);
  }
}
