"""
GENERATED BY MEMBRA L0 SDK FACTORY

Python MEMBRA L0 client adapter.

This client does not custody funds.
It builds local proof objects and prepares Solana-devnet-compatible payloads.
"""

from __future__ import annotations

import hashlib
import json
import time
import uuid
from dataclasses import dataclass, asdict, field
from typing import Any, Dict, List, Optional


MEMBRA_NETWORK = "MEMBRA"
MEMBRA_DEFAULT_RPC = "https://api.devnet.solana.com"


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8", errors="ignore")).hexdigest()


def sha256_json(value: Any) -> str:
    return hashlib.sha256(
        json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()


@dataclass
class MIR:
    mir_id: str = field(default_factory=lambda: "mir_" + uuid.uuid4().hex)
    job_id: str = field(default_factory=lambda: "job_" + uuid.uuid4().hex)
    agent_id: str = "agent_unknown"
    input_hash: str = ""
    context_hash: str = ""
    output_hash: str = ""
    model_id_hash: str = ""
    policy_tier: str = "Low"
    selected_m5_nodes: List[str] = field(default_factory=list)
    quorum_required: int = 1
    quorum_reached: bool = False
    created_at: int = field(default_factory=lambda: int(time.time()))
    devnet_tx: Optional[str] = None

    def root(self) -> str:
        return sha256_json(asdict(self))


@dataclass
class M5NodeClaim:
    node_id: str
    authority: str
    hardware_hash: str
    model_manifest_hash: str
    stake_score: int
    reputation_score: int = 100

    def root(self) -> str:
        return sha256_json(asdict(self))


@dataclass
class MCR:
    mcr_id: str = field(default_factory=lambda: "mcr_" + uuid.uuid4().hex)
    owner_wallet: str = "unknown"
    repo_merkle_root: str = ""
    memory_root: str = ""
    mir_roots: List[str] = field(default_factory=list)
    m5_attestation_root: str = ""
    collateral_score: int = 0
    appraisal_low_usd: int = 0
    appraisal_high_usd: int = 0
    created_at: int = field(default_factory=lambda: int(time.time()))
    devnet_tx: Optional[str] = None

    def root(self) -> str:
        return sha256_json(asdict(self))


class MembraL0Client:
    def __init__(self, rpc_url: str = MEMBRA_DEFAULT_RPC):
        self.rpc_url = rpc_url
        self.local_mirs: Dict[str, MIR] = {}
        self.local_mcrs: Dict[str, MCR] = {}

    def create_mir(
        self,
        agent_id: str,
        prompt_or_job_summary: str,
        context_summary: str,
        model_id: str,
        policy_tier: str = "Low",
        selected_m5_nodes: Optional[List[str]] = None,
        quorum_required: int = 1,
    ) -> MIR:
        mir = MIR(
            agent_id=agent_id,
            input_hash=sha256_text(prompt_or_job_summary),
            context_hash=sha256_text(context_summary),
            model_id_hash=sha256_text(model_id),
            policy_tier=policy_tier,
            selected_m5_nodes=selected_m5_nodes or [],
            quorum_required=quorum_required,
        )
        self.local_mirs[mir.mir_id] = mir
        return mir

    def complete_mir(self, mir_id: str, output_summary: str, quorum_reached: bool = True) -> MIR:
        mir = self.local_mirs[mir_id]
        mir.output_hash = sha256_text(output_summary)
        mir.quorum_reached = quorum_reached
        return mir

    def create_mcr(
        self,
        owner_wallet: str,
        repo_merkle_root: str,
        memory_root: str,
        mir_ids: List[str],
        m5_attestation_root: str,
        collateral_score: int,
        appraisal_low_usd: int,
        appraisal_high_usd: int,
    ) -> MCR:
        mir_roots = [self.local_mirs[mid].root() for mid in mir_ids]
        mcr = MCR(
            owner_wallet=owner_wallet,
            repo_merkle_root=repo_merkle_root,
            memory_root=memory_root,
            mir_roots=mir_roots,
            m5_attestation_root=m5_attestation_root,
            collateral_score=collateral_score,
            appraisal_low_usd=appraisal_low_usd,
            appraisal_high_usd=appraisal_high_usd,
        )
        self.local_mcrs[mcr.mcr_id] = mcr
        return mcr

    def prepare_solana_payload(self, obj: Any) -> Dict[str, Any]:
        """
        Returns a Solana-devnet-ready payload.
        Actual signing/sending is handled by the TypeScript Anchor client
        or a local Solana signer.
        """
        data = asdict(obj)
        return {
            "network": MEMBRA_NETWORK,
            "cluster": "solana-devnet",
            "object_type": obj.__class__.__name__,
            "object_root": obj.root(),
            "payload": data,
            "raw_private_data_included": False,
        }
