"""initial_schema

Revision ID: a81cc7aca59b
Revises: 
Create Date: 2026-05-17 00:38:30.463620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.base import GUID


# revision identifiers, used by Alembic.
revision: str = 'a81cc7aca59b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('agent_type', sa.Enum('STRATEGY', 'PRODUCT', 'ENGINEERING', 'OPERATIONS', 'SALES', 'FINANCE', 'LEGAL_RISK', 'GOVERNANCE', 'PROOF', 'CONCIERGE', name='agenttype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('REGISTERED', 'ACTIVE', 'PAUSED', 'REVOKED', name='agentstatus'), nullable=True),
    sa.Column('llm_provider', sa.String(length=32), nullable=True),
    sa.Column('llm_model', sa.String(length=64), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('allowed_actions', sa.JSON(), nullable=True),
    sa.Column('blocked_actions', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('company_id', GUID(length=36), nullable=True),
    sa.Column('department_id', GUID(length=36), nullable=True),
    sa.Column('owner_wallet', sa.String(length=42), nullable=True),
    sa.Column('version', sa.String(length=16), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SUSPENDED', 'DISSOLVED', name='companystatus'), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('owner_wallet', sa.String(length=42), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_owner_wallet'), 'companies', ['owner_wallet'], unique=False)
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('departments',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('company_id', GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dept_type', sa.Enum('STRATEGY', 'PRODUCT', 'ENGINEERING', 'OPERATIONS', 'SALES', 'FINANCE', 'LEGAL_RISK', 'GOVERNANCE', 'PROOF', 'CONCIERGE', name='departmenttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lead_agent_id', GUID(length=36), nullable=True),
    sa.Column('sop_count', sa.Integer(), nullable=True),
    sa.Column('active_task_count', sa.Integer(), nullable=True),
    sa.Column('kpi_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workforce_employees',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('department', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('responsibilities', sa.JSON(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('total_contributions', sa.Integer(), nullable=False),
    sa.Column('last_output', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workforce_employees_department'), 'workforce_employees', ['department'], unique=False)
    op.create_index(op.f('ix_workforce_employees_employee_id'), 'workforce_employees', ['employee_id'], unique=True)
    op.create_table('agent_tools',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('agent_id', GUID(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('tool_description', sa.Text(), nullable=True),
    sa.Column('tool_schema', sa.JSON(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('requires_human_approval', sa.Boolean(), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_memories',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('company_id', GUID(length=36), nullable=False),
    sa.Column('memory_type', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('importance_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source_agent_id', GUID(length=36), nullable=True),
    sa.Column('proof_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escalation_rules',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('company_id', GUID(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trigger_condition', sa.String(length=255), nullable=False),
    sa.Column('trigger_rules', sa.JSON(), nullable=True),
    sa.Column('escalation_path', sa.JSON(), nullable=True),
    sa.Column('notify_wallets', sa.JSON(), nullable=True),
    sa.Column('auto_action', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('initiatives',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('company_id', GUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PROPOSED', 'APPROVED', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', name='initiativestatus'), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('target_kpi_json', sa.JSON(), nullable=True),
    sa.Column('bottleneck_notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpi_records',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('company_id', GUID(length=36), nullable=False),
    sa.Column('kpi_name', sa.String(length=255), nullable=False),
    sa.Column('kpi_category', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('proof_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proof_chains',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('company_id', GUID(length=36), nullable=True),
    sa.Column('chain_name', sa.String(length=255), nullable=False),
    sa.Column('chain_type', sa.String(length=64), nullable=True),
    sa.Column('genesis_hash', sa.String(length=64), nullable=False),
    sa.Column('latest_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_count', sa.String(length=16), nullable=True),
    sa.Column('anchored_to', sa.String(length=255), nullable=True),
    sa.Column('anchor_tx', sa.String(length=66), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sops',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('company_id', GUID(length=36), nullable=False),
    sa.Column('department_id', GUID(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('triggers', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('SUPERADMIN', 'ADMIN', 'OPERATOR', 'AGENT', 'REVIEWER', 'CONTRACTOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('organization_id', GUID(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    op.create_table('vendors',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('company_id', GUID(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vendor_type', sa.String(length=64), nullable=False),
    sa.Column('contact_json', sa.JSON(), nullable=True),
    sa.Column('wallet_address', sa.String(length=42), nullable=True),
    sa.Column('service_areas', sa.JSON(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workforce_contributions',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=32), nullable=False),
    sa.Column('department', sa.String(length=32), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.String(length=256), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['workforce_employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workforce_contributions_department'), 'workforce_contributions', ['department'], unique=False)
    op.create_index(op.f('ix_workforce_contributions_employee_id'), 'workforce_contributions', ['employee_id'], unique=False)
    op.create_table('workforce_tasks',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=32), nullable=False),
    sa.Column('department', sa.String(length=32), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['workforce_employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workforce_tasks_department'), 'workforce_tasks', ['department'], unique=False)
    op.create_index(op.f('ix_workforce_tasks_employee_id'), 'workforce_tasks', ['employee_id'], unique=False)
    op.create_table('world_assets',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('company_id', GUID(length=36), nullable=True),
    sa.Column('owner_wallet', sa.String(length=42), nullable=False),
    sa.Column('asset_type', sa.Enum('APARTMENT', 'VEHICLE', 'WINDOW', 'WEARABLE', 'TOOL', 'STORAGE', 'PICKUP_NODE', 'MICRO_WAREHOUSE', 'SURFACE', 'DEVICE', 'ROUTE', name='assettype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('UNREGISTERED', 'AVAILABLE', 'IN_USE', 'MAINTENANCE', 'RETIRED', name='assetstatus'), nullable=True),
    sa.Column('location_json', sa.JSON(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('media_cids', sa.JSON(), nullable=True),
    sa.Column('proof_hash', sa.String(length=64), nullable=True),
    sa.Column('kpi_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_assets_owner_wallet'), 'world_assets', ['owner_wallet'], unique=False)
    op.create_table('approval_gates',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('gate_type', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', GUID(length=36), nullable=False),
    sa.Column('requester_id', GUID(length=36), nullable=True),
    sa.Column('requester_agent_id', GUID(length=36), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'ESCALATED', 'AUTO_APPROVED', 'EXPIRED', name='approvalstatus'), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=True),
    sa.Column('approvers', sa.JSON(), nullable=True),
    sa.Column('required_approvals', sa.Integer(), nullable=True),
    sa.Column('current_approvals', sa.Integer(), nullable=True),
    sa.Column('rejections', sa.Integer(), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('auto_expire_hours', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proof_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requester_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_listings',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('asset_id', GUID(length=36), nullable=False),
    sa.Column('listing_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('visibility', sa.String(length=32), nullable=True),
    sa.Column('owner_consent', sa.Boolean(), nullable=True),
    sa.Column('governance_approved', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['world_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_proofs',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('asset_id', GUID(length=36), nullable=False),
    sa.Column('proof_type', sa.String(length=64), nullable=False),
    sa.Column('proof_data', sa.JSON(), nullable=True),
    sa.Column('ipfs_cid', sa.String(length=64), nullable=True),
    sa.Column('verification_status', sa.String(length=32), nullable=True),
    sa.Column('proof_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['world_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_reservations',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('asset_id', GUID(length=36), nullable=False),
    sa.Column('reserved_by', GUID(length=36), nullable=True),
    sa.Column('reservation_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cost', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('proof_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['world_assets.id'], ),
    sa.ForeignKeyConstraint(['reserved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('user_id', GUID(length=36), nullable=True),
    sa.Column('wallet_address', sa.String(length=42), nullable=True),
    sa.Column('organization_id', GUID(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('proof_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_wallet_address'), 'audit_logs', ['wallet_address'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('consent_type', sa.Enum('OWNER_VISIBILITY', 'DATA_SHARING', 'SETTLEMENT_AUTH', 'ASSET_USE', 'AI_DECISION', name='consenttype'), nullable=False),
    sa.Column('owner_wallet', sa.String(length=42), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', GUID(length=36), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=True),
    sa.Column('granted_by', GUID(length=36), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proof_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_owner_wallet'), 'consent_records', ['owner_wallet'], unique=False)
    op.create_table('decision_events',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('company_id', GUID(length=36), nullable=True),
    sa.Column('decision_type', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', GUID(length=36), nullable=False),
    sa.Column('decision_maker_type', sa.String(length=16), nullable=False),
    sa.Column('decision_maker_id', GUID(length=36), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('alternatives', sa.JSON(), nullable=True),
    sa.Column('selected_option', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.String(length=16), nullable=True),
    sa.Column('human_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', GUID(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proof_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intents',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_json', sa.JSON(), nullable=True),
    sa.Column('structured_objective_json', sa.JSON(), nullable=True),
    sa.Column('user_wallet', sa.String(length=42), nullable=True),
    sa.Column('user_id', GUID(length=36), nullable=True),
    sa.Column('status', sa.Enum('RAW', 'PARSED', 'STRUCTURED', 'OBJECTIVES_CREATED', 'ARCHIVED', name='intentstatus'), nullable=True),
    sa.Column('confidence_score', sa.String(length=16), nullable=True),
    sa.Column('llm_provider', sa.String(length=32), nullable=True),
    sa.Column('llm_model', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intents_user_wallet'), 'intents', ['user_wallet'], unique=False)
    op.create_table('people',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('user_id', GUID(length=36), nullable=True),
    sa.Column('wallet_address', sa.String(length=42), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('availability_json', sa.JSON(), nullable=True),
    sa.Column('location_json', sa.JSON(), nullable=True),
    sa.Column('reputation_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('task_completed_count', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_wallet_address'), 'people', ['wallet_address'], unique=False)
    op.create_table('policies',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('company_id', GUID(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DEPRECATED', 'EMERGENCY', name='policystatus'), nullable=True),
    sa.Column('policy_type', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('applies_to', sa.JSON(), nullable=True),
    sa.Column('enforcement_mode', sa.String(length=32), nullable=True),
    sa.Column('created_by', GUID(length=36), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proofbook_entries',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('entry_type', sa.Enum('TASK_CREATED', 'TASK_COMPLETED', 'AGENT_ACTION', 'APPROVAL_GRANTED', 'APPROVAL_REJECTED', 'POLICY_APPLIED', 'LISTING_PUBLISHED', 'JOB_COMPLETED', 'SETTLEMENT_TRIGGERED', 'KPI_RECORDED', 'CONSENT_GRANTED', 'CONSENT_REVOKED', 'ASSET_RESERVED', 'DECISION_MADE', 'EXTERNAL_SETTLEMENT', name='proofentrytype'), nullable=False),
    sa.Column('company_id', GUID(length=36), nullable=True),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', GUID(length=36), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', GUID(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('ipfs_cid', sa.String(length=64), nullable=True),
    sa.Column('proof_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('chain_id', GUID(length=36), nullable=True),
    sa.Column('block_number', sa.String(length=64), nullable=True),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['proof_chains.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proofbook_entries_proof_hash'), 'proofbook_entries', ['proof_hash'], unique=False)
    op.create_table('risk_classifications',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', GUID(length=36), nullable=False),
    sa.Column('risk_type', sa.String(length=64), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('flagged_by', GUID(length=36), nullable=True),
    sa.Column('flagged_agent_id', GUID(length=36), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['flagged_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['flagged_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('user_id', GUID(length=36), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_jti'), 'sessions', ['jti'], unique=True)
    op.create_table('objectives',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('intent_id', GUID(length=36), nullable=False),
    sa.Column('company_id', GUID(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'FAILED', name='objectivestatus'), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('target_completion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('success_criteria', sa.JSON(), nullable=True),
    sa.Column('assigned_department', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('company_id', GUID(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('route_type', sa.String(length=64), nullable=False),
    sa.Column('waypoints', sa.JSON(), nullable=True),
    sa.Column('vehicle_asset_id', GUID(length=36), nullable=True),
    sa.Column('driver_person_id', GUID(length=36), nullable=True),
    sa.Column('schedule_json', sa.JSON(), nullable=True),
    sa.Column('estimated_duration_min', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['driver_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['vehicle_asset_id'], ['world_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('objective_id', GUID(length=36), nullable=True),
    sa.Column('company_id', GUID(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Enum('AI_ANALYSIS', 'HUMAN_WORK', 'API_CALL', 'GOVERNANCE_GATE', 'PROOF_COLLECTION', 'SETTLEMENT_TRIGGER', 'ASSET_DEPLOYMENT', 'COMMUNICATION', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('BACKLOG', 'TODO', 'IN_PROGRESS', 'REVIEW', 'BLOCKED', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('owner_id', GUID(length=36), nullable=True),
    sa.Column('owner_agent_id', GUID(length=36), nullable=True),
    sa.Column('estimated_hours', sa.String(length=16), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proof_requirement', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.ForeignKeyConstraint(['owner_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('task_id', GUID(length=36), nullable=True),
    sa.Column('company_id', GUID(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('job_type', sa.Enum('BOUNTY', 'WORK_ORDER', 'MARKETPLACE_LISTING', 'ADMIN_REVIEW', 'FULFILLMENT', 'KPI_ANALYSIS', 'APARTMENT_TASK', 'CAR_AD_TASK', 'WINDOW_AD_TASK', 'WEARABLE_TASK', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'ASSIGNED', 'IN_PROGRESS', 'REVIEW', 'COMPLETED', 'CANCELLED', 'DISPUTED', name='jobstatus'), nullable=True),
    sa.Column('budget', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payout_eligible', sa.Boolean(), nullable=True),
    sa.Column('payout_amount', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('assigned_to', GUID(length=36), nullable=True),
    sa.Column('assigned_agent_id', GUID(length=36), nullable=True),
    sa.Column('asset_id', GUID(length=36), nullable=True),
    sa.Column('location_json', sa.JSON(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('deliverables', sa.JSON(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proof_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['world_assets.id'], ),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objective_task_links',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('objective_id', GUID(length=36), nullable=False),
    sa.Column('task_id', GUID(length=36), nullable=False),
    sa.Column('link_type', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_assignments',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('task_id', GUID(length=36), nullable=False),
    sa.Column('assignee_type', sa.String(length=16), nullable=False),
    sa.Column('assignee_id', GUID(length=36), nullable=False),
    sa.Column('assigned_by', GUID(length=36), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_dependencies',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('task_id', GUID(length=36), nullable=False),
    sa.Column('depends_on_task_id', GUID(length=36), nullable=False),
    sa.Column('dependency_type', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_proofs',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('task_id', GUID(length=36), nullable=False),
    sa.Column('proof_type', sa.String(length=64), nullable=False),
    sa.Column('proof_data', sa.JSON(), nullable=True),
    sa.Column('ipfs_cid', sa.String(length=64), nullable=True),
    sa.Column('verification_status', sa.String(length=32), nullable=True),
    sa.Column('verified_by', GUID(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proof_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_action_logs',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('agent_id', GUID(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('task_id', GUID(length=36), nullable=True),
    sa.Column('job_id', GUID(length=36), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('proof_hash', sa.String(length=64), nullable=True),
    sa.Column('governance_gate_passed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bounties',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('job_id', GUID(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reward_amount', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('submissions_count', sa.Integer(), nullable=True),
    sa.Column('winner_id', GUID(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_proofs',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('job_id', GUID(length=36), nullable=False),
    sa.Column('proof_type', sa.String(length=64), nullable=False),
    sa.Column('proof_data', sa.JSON(), nullable=True),
    sa.Column('ipfs_cid', sa.String(length=64), nullable=True),
    sa.Column('verification_status', sa.String(length=32), nullable=True),
    sa.Column('verified_by', GUID(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proof_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_actions',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('job_id', GUID(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=False),
    sa.Column('asset_id', GUID(length=36), nullable=True),
    sa.Column('listing_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('visibility', sa.String(length=32), nullable=True),
    sa.Column('owner_consent', sa.Boolean(), nullable=True),
    sa.Column('governance_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['world_assets.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_orders',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('job_id', GUID(length=36), nullable=True),
    sa.Column('wo_number', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('crew_assignment', sa.JSON(), nullable=True),
    sa.Column('schedule_json', sa.JSON(), nullable=True),
    sa.Column('equipment_json', sa.JSON(), nullable=True),
    sa.Column('cost_estimate', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wo_number')
    )
    op.create_table('settlement_eligibilities',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('job_id', GUID(length=36), nullable=True),
    sa.Column('work_order_id', GUID(length=36), nullable=True),
    sa.Column('bounty_id', GUID(length=36), nullable=True),
    sa.Column('recipient_wallet', sa.String(length=42), nullable=True),
    sa.Column('recipient_user_id', GUID(length=36), nullable=True),
    sa.Column('eligible_amount', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('criteria_met', sa.JSON(), nullable=True),
    sa.Column('governance_approved', sa.Boolean(), nullable=True),
    sa.Column('proof_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_tx_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlement_records',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('company_id', GUID(length=36), nullable=True),
    sa.Column('eligibility_id', GUID(length=36), nullable=True),
    sa.Column('job_id', GUID(length=36), nullable=True),
    sa.Column('recipient_type', sa.String(length=16), nullable=False),
    sa.Column('recipient_id', GUID(length=36), nullable=False),
    sa.Column('recipient_wallet', sa.String(length=42), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('rail', sa.Enum('STRIPE', 'SOLANA', 'ETHEREUM', 'BANK_TRANSFER', 'CRYPTO_OTHER', name='settlementrail'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ELIGIBLE', 'INSTRUCTIONS_SENT', 'PROCESSING', 'SETTLED', 'FAILED', 'DISPUTED', name='settlementstatus'), nullable=True),
    sa.Column('instructions_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_tx_id', sa.String(length=255), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('proof_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['eligibility_id'], ['settlement_eligibilities.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_rail_logs',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('settlement_id', GUID(length=36), nullable=False),
    sa.Column('rail', sa.Enum('STRIPE', 'SOLANA', 'ETHEREUM', 'BANK_TRANSFER', 'CRYPTO_OTHER', name='settlementrail'), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.String(length=16), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlement_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payout_instructions',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('settlement_id', GUID(length=36), nullable=False),
    sa.Column('instruction_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_code', sa.String(length=16), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlement_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payout_instructions')
    op.drop_table('external_rail_logs')
    op.drop_table('settlement_records')
    op.drop_table('settlement_eligibilities')
    op.drop_table('work_orders')
    op.drop_table('marketplace_actions')
    op.drop_table('job_proofs')
    op.drop_table('bounties')
    op.drop_table('agent_action_logs')
    op.drop_table('task_proofs')
    op.drop_table('task_dependencies')
    op.drop_table('task_assignments')
    op.drop_table('objective_task_links')
    op.drop_table('jobs')
    op.drop_table('tasks')
    op.drop_table('routes')
    op.drop_table('objectives')
    op.drop_index(op.f('ix_sessions_jti'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('risk_classifications')
    op.drop_index(op.f('ix_proofbook_entries_proof_hash'), table_name='proofbook_entries')
    op.drop_table('proofbook_entries')
    op.drop_table('policies')
    op.drop_index(op.f('ix_people_wallet_address'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_intents_user_wallet'), table_name='intents')
    op.drop_table('intents')
    op.drop_table('decision_events')
    op.drop_index(op.f('ix_consent_records_owner_wallet'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_audit_logs_wallet_address'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('asset_reservations')
    op.drop_table('asset_proofs')
    op.drop_table('asset_listings')
    op.drop_table('approval_gates')
    op.drop_index(op.f('ix_world_assets_owner_wallet'), table_name='world_assets')
    op.drop_table('world_assets')
    op.drop_index(op.f('ix_workforce_tasks_employee_id'), table_name='workforce_tasks')
    op.drop_index(op.f('ix_workforce_tasks_department'), table_name='workforce_tasks')
    op.drop_table('workforce_tasks')
    op.drop_index(op.f('ix_workforce_contributions_employee_id'), table_name='workforce_contributions')
    op.drop_index(op.f('ix_workforce_contributions_department'), table_name='workforce_contributions')
    op.drop_table('workforce_contributions')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_table('users')
    op.drop_table('sops')
    op.drop_table('proof_chains')
    op.drop_table('kpi_records')
    op.drop_table('initiatives')
    op.drop_table('escalation_rules')
    op.drop_table('company_memories')
    op.drop_table('agent_tools')
    op.drop_index(op.f('ix_workforce_employees_employee_id'), table_name='workforce_employees')
    op.drop_index(op.f('ix_workforce_employees_department'), table_name='workforce_employees')
    op.drop_table('workforce_employees')
    op.drop_table('departments')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_index(op.f('ix_companies_owner_wallet'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('agents')
    # ### end Alembic commands ###
